# Full documentation https://wiki.hyprland.org

source = ~/.config/hypr/conf/animations.conf
source = ~/.config/hypr/conf/autostart.conf
source = ~/.config/hypr/conf/binds.conf
source = ~/.config/hypr/conf/decoration.conf
source = ~/.config/hypr/conf/env.conf
source = ~/.config/hypr/conf/general.conf
source = ~/.config/hypr/conf/input.conf
source = ~/.config/hypr/conf/layouts.conf
source = ~/.config/hypr/conf/misc.conf
source = ~/.config/hypr/conf/monitor.conf
source = ~/.config/hypr/conf/windowrules.conf

